### ISSUE TITLE
Error for UpdateAsync, Windows Phone 8.1 RT, Azure Mobile Services SQLiteStore

### ISSUE THREAD

**Issue by kaki104** [Azure/azure-mobile-services#544]
Hi
I using Azure Mobile Services SQLiteStore nuget package.

1. My project is Universal project.
2. ViewModel in shared project
3. No error during runtime Windows 8.1 project, but, raise error in Windows Phone 8.1 project

This is source code

       public async void AddRecent(MstFolderMWrap addItem)
        {
            //최근 항목에 이미 존재하는 아이템이라면 삭제하고 맨위로 올림
            MstFolderMWrap exist = RecentFolders.FirstOrDefault(p => p.Id.Equals(addItem.Id));
            if (exist != null)
            {
                RecentFolders.Remove(exist);
                RecentFolders.Insert(0, exist);

                var Id = string.Format("{0}_{1}", _liveUser.Id, exist.Id);
                var existRec = await RecentTableSync.LookupAsync(Id);
                await RecentTableSync.UpdateAsync(existRec);
                //var deleteItem =
                //    await RecentTableSync.LookupAsync(string.Format("{0}_{1}", _liveUser.Id, exist.Id));
                //await RecentTableSync.DeleteAsync(deleteItem);
                //await App.MobileService.SyncContext.PushAsync();
            }
            else
            {
                RecentFolders.Insert(0, addItem);
                await RecentTableSync.InsertAsync(new HstUserRecentWrap
                {
                    Id = string.Format("{0}_{1}", _liveUser.Id, addItem.Id),
                });
            }
            await App.MobileService.SyncContext.PushAsync();
        }

-2146233088

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncContext.<ExecuteSyncAction>d__3b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncContext.<PushAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at OneSearch.Universal.Helpers.PublicHelper.<AddRecent>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__3(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()

and error screenshot
http://1drv.ms/1xBzltI

If this issue is run PushAsync after the UpdateAsync, you would need to call the Push Web method in the Windows Phone Library, seems to call Post Web method.

Thank you
Park

**Comment by kaki104** [comment]
Hi
When I see a post by improving the synchronization part no longer causes an error.
http://azure.microsoft.com/en-us/documentation/articles/mobile-services-windows-store-dotnet-get-started-offline-data/
I think it is wrong to write code in which the error occurred.
Thank you
