### ISSUE TITLE
WP81 - IMobileServiceSyncTable sorting in release build exception

### ISSUE THREAD

**Issue by raketenhunddev** [Azure/azure-mobile-services#548]
I get the following exception when I'm trying to use IMobileServiceSyncTable.OrderByDescending(() => item => item.PostingDate).ToListAsync() where PostingDate is a DateTime property: "System.Resources.MissingManifestResourceException".

   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at Microsoft.WindowsAzure.MobileServices.Resources.get_ODataExpressionParser_IdentifierExpected()
   at Microsoft.WindowsAzure.MobileServices.Query.ODataExpressionParser.ParseIdentifier()
   at Microsoft.WindowsAzure.MobileServices.Query.ODataExpressionParser.ParsePrimaryStart()
   at Microsoft.WindowsAzure.MobileServices.Query.ODataExpressionParser.ParsePrimary()
   at Microsoft.WindowsAzure.MobileServices.Query.ODataExpressionParser.ParseUnary()
   at Microsoft.WindowsAzure.MobileServices.Query.ODataExpressionParser.ParseMultiplicative()
   at Microsoft.WindowsAzure.MobileServices.Query.ODataExpressionParser.ParseAdditive()
   at Microsoft.WindowsAzure.MobileServices.Query.ODataExpressionParser.ParseComparison()
   at Microsoft.WindowsAzure.MobileServices.Query.ODataExpressionParser.ParseLogicalAnd()
   at Microsoft.WindowsAzure.MobileServices.Query.ODataExpressionParser.ParseLogicalOr()
   at Microsoft.WindowsAzure.MobileServices.Query.ODataExpressionParser.ParseOrderBy()
   at Microsoft.WindowsAzure.MobileServices.Query.MobileServiceTableQueryDescription.Parse(String tableName, String query, String uriPath)
   at Microsoft.WindowsAzure.MobileServices.Query.MobileServiceTableQueryDescription.Parse(String tableName, String query)
   at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncContext.<ReadAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.WindowsAzure.MobileServices.Query.MobileServiceTableQueryProvider.<Execute>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.WindowsAzure.MobileServices.Query.MobileServiceTableQueryProvider.<Execute>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.WindowsAzure.MobileServices.Query.MobileServiceTableQuery`1.<ToListAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Postings.Universal.ViewModels.EntryViewModel.<Start>d__0.MoveNext()

This error only occurs on a Windows Phone 8.1 device in release mode. When deploying a debug build, everything works fine! To sort the list in a release build I have to use IMobileServiceSyncTable.ToListAsync and then I'm able to sort the list. Am I doing something wrong?

**Comment by lindydonna** [comment]
I think you are running into a bug in the .NET runtime on Windows Phone. See this thread for more details: https://social.msdn.microsoft.com/Forums/en-US/88920ec1-0088-43d0-8d39-cc3c292fcb9f/offline-data-sample-crashes-on-startup?forum=azuremobile

We have fixed the bug in the source, so you can build your own client assembly. Otherwise, we will release a new NuGet package within a week or so.

**Comment by raketenhunddev** [comment]
I think I'll wait for the NuGet update. Thanks for your response

**Comment by lindydonna** [comment]
Fixed in 1.3.1 of Mobile Services SDK and 1.0.1 of SQLiteStore.

**Comment by hemlata09** [comment]
Hi,

I am facing same issue with my app in Release mode and updated Mobile Service SDK 1.3.1 and SQLiteStore 1.0.1 then its working fine. After that I deployed on App store with updated dlls but its throwing same exception (MissingManifestResource_NoPRIresources) after installing on Windows Phone.

Can you please provide any solution?

Thanks,
Hema
