### ISSUE TITLE
Runtime error after including the dependency of azure mobile service into gradle

### ISSUE THREAD

**Issue by vickymitra786** [Azure/azure-mobile-services#693]
# Observation:
- The app has login authentication mechanism using native sdk for facebook and twitter(fabric.io).
- Everything is working fine until and unless azure mobile service is added into the gradle file.
- I have tested out the azure mobile service on a demo project where the login authentication mechanism was using azure mobile sdk alone and it worked flawlessly.
- My aim over here is to get the native sdk do the login authentication and then direct the obtained token to the azure which further handles the operation.

# Gradle Code:
```
import java.util.regex.Pattern

apply plugin: 'com.android.application'

//Put Fabric plugin after Android plugin
apply plugin: 'io.fabric'
// For the TRIPLE-T gradle demo
apply plugin: 'play'


android {
    compileSdkVersion 21
    buildToolsVersion '21.1.2'

    dexOptions {
        javaMaxHeapSize "4g"
    }

    defaultConfig {
        applicationId "com.xxx.xxx.xxx"
        minSdkVersion 16
        targetSdkVersion 21
        multiDexEnabled true
        /*versionCode 5
        versionName "5.0"*/
    }
    signingConfigs {
        release {
            storeFile file('xxx')
            storePassword 'xxx'
            keyAlias 'xxx'
            keyPassword 'xxx'
        }
    }
    buildTypes {

        debug {
            // enable crashlytics where you need
            buildConfigField "boolean", "USE_CRASHLYTICS", "false"
            ext.enableCrashlytics = false
        }
        release {
            buildConfigField "boolean", "USE_CRASHLYTICS", "false"
            ext.enableCrashlytics = false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release // dont forget to
        }
    }
    packagingOptions {
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/NOTICE'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }

    lintOptions {
        abortOnError false
    }


}



buildscript {
    repositories {
        mavenCentral()
        jcenter{ url 'http://jcenter.bintray.com'}
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        // ...
        classpath 'com.github.triplet.gradle:play-publisher:1.0.2'

          classpath 'com.android.tools.build:gradle:1.0.0'
        // The Fabric Gradle plugin uses an open ended version to
        // react quickly to Android tooling updates
        classpath 'io.fabric.tools:gradle:1.+'

    }
}

repositories {
    jcenter()
    maven { url 'https://maven.fabric.io/public' }
}
play {
    serviceAccountEmail = '652675572315-qh0gfcfkr0cvengpefesab5e45g6eo12@developer.gserviceaccount.com'
    pk12File = file('ed640d0b698a.p12')
    track = 'beta' // or 'beta' or 'alpha' or 'production'
}



dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.facebook.android:facebook-android-sdk:3.22.0'
    compile 'com.readystatesoftware.sqliteasset:sqliteassethelper:2.0.1'
    compile 'com.google.android.gms:play-services:+'
    compile 'com.nostra13.universalimageloader:universal-image-loader:1.9.3'
    compile 'net.hockeyapp.android:HockeySDK:3.5.0-b.4'
    compile 'eu.the4thfloor.volley:com.android.volley:2015.01.06'
    compile 'joda-time:joda-time:2.7'
    //compile 'org.twitter4j:twitter4j-core:4.0.2'
    compile 'com.viewpagerindicator:library:2.4.1'
    compile files('src/main/libs/pinchzoom.jar')
    compile files('src/main/libs/YouTubeAndroidPlayerApi.jar')
    compile files('src/main/libs/sample-2.3.1-sources.jar')
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile 'com.readystatesoftware.systembartint:systembartint:1.0.4'
    compile('com.twitter.sdk.android:twitter:1.3.0@aar') {
        transitive = true;
    }
    compile files('src/main/libs/mobile-engagement-3.0.0.jar')
    compile 'com.android.support:cardview-v7:21.0.3'
    compile 'com.github.castorflex.smoothprogressbar:library:1.1.0'
    compile 'com.microsoft.azure:azure-mobile-services-android-sdk:2.0.2-beta2'
}


task('increaseVersionCode') << {
    def manifestFile = file("src/main/AndroidManifest.xml")
    def pattern = Pattern.compile("versionCode=\"(\\d+)\"")
    def manifestText = manifestFile.getText()
    def matcher = pattern.matcher(manifestText)
    matcher.find()
    def versionCode = Integer.parseInt(matcher.group(1))
    android.defaultConfig.versionCode = versionCode + 1
    println "Setting version code to ${android.defaultConfig.versionCode}"
    def manifestContent = matcher.replaceAll("versionCode=\"" + android.defaultConfig.versionCode + "\"")
    manifestFile.write(manifestContent)
}

task('setVersionName') << {

    def git = 'git describe --abbrev=7 --tags'

    def proc = git.execute()
    proc.waitFor()
    def desc = "${proc.in.text}".trim()

    if (desc.isEmpty()) {
        println "ERROR setting version name"
        return
    }

    def manifestFile = file("src/main/AndroidManifest.xml")
    def pattern = Pattern.compile("versionName=\"(.*)\"")
    def manifestText = manifestFile.getText()
    def matcher = pattern.matcher(manifestText)
    matcher.find()
    println "Setting version name to ${desc}"
    def manifestContent = matcher.replaceAll("versionName=\"" + desc + "\"")
    manifestFile.write(manifestContent)
}

tasks.whenTaskAdded { task ->
    if (task.name == 'generateReleaseBuildConfig') {
        task.dependsOn 'increaseVersionCode'
        task.dependsOn 'setVersionName'
    }
}

```

# Error Log:
```
 java.lang.NoClassDefFoundError: com.twitter.sdk.android.core.internal.SessionMonitor$AccountServiceProvider
            at com.twitter.sdk.android.core.internal.SessionMonitor.<init>(SessionMonitor.java:36)
            at com.twitter.sdk.android.core.TwitterCore.onPreExecute(TwitterCore.java:100)
            at io.fabric.sdk.android.InitializationTask.onPreExecute(InitializationTask.java:27)
            at io.fabric.sdk.android.services.concurrency.AsyncTask.executeOnExecutor(AsyncTask.java:594)
            at io.fabric.sdk.android.services.concurrency.PriorityAsyncTask.executeOnExecutor(PriorityAsyncTask.java:26)
            at io.fabric.sdk.android.Kit.initialize(Kit.java:49)
            at io.fabric.sdk.android.Fabric.initializeKits(Fabric.java:417)
            at io.fabric.sdk.android.Fabric.init(Fabric.java:364)
            at io.fabric.sdk.android.Fabric.setFabric(Fabric.java:321)
            at io.fabric.sdk.android.Fabric.with(Fabric.java:292)
            at com.makeitnow.justfollow.sociallog.ApplicationClass.onCreate(ApplicationClass.java:224)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4328)
            at android.app.ActivityThread.access$1500(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5001)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
```

# Observed:

- The error points to the onCreate(..) method of Custom Application class which extends Android's  Application Class where I have initialized the Twitter Object using Fabric.io .
- I can't remove the Custom Application class as its associated with other important modules

Would be obliged if one can help me out of this mess

**Comment by vickymitra786** [comment]
I would also like to take this opportunity to ask that approximately around when can we expect to get the client-side authentication support for twitter.

**Comment by ysxu** [comment]
@vickymitra786 have you tried following https://azure.microsoft.com/en-us/documentation/articles/mobile-services-android-get-started-users/? We do offer support for twitter auth :).

**Comment by paulbatum** [comment]
@ysxu You linked to the server flow. Mobile Services does not support the twitter client flow, but Mobile Apps does, using the authentication/authorization feature of app service. Unfortunately the official documentation does not indicate this yet :(

I am closing this issue due to its age. If the problem still exists please file a issue in our new Android client SDK repository: 
https://github.com/azure/azure-mobile-apps-android-client
